use_frameworks!

target 'RevolutionRoboticsBluetooth_Example' do
  pod 'RevolutionRoboticsBluetooth', :path => '../'

  target 'RevolutionRoboticsBluetooth_Tests' do
    inherit! :search_paths

    
  end
end
